# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 395d124fd672467dc918bdebf897259339d580b9eda12eb6c2f9bde75f459e5f7c6ddfbad017a1103282e9c7c0f58c781260ba4585c775fd1b6ccd3567ddc5ae

test:
  secret_key_base: 676d1a41929de4f26f52a21e897e3b206f56bd6f28445153c597f886f98d7678a12bd680c1b1e33bef30e6cf714b241b278f57fb9983c51ec987ede4721a6c49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
